In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
data = pd.read_csv('ssi_results_bak.csv')

In [11]:
data

,mouse_id,session_id,cluster_id,best_channel,n_spikes,si,ssi,p_value
0,7010,m1,0,0,71291,0.012321,17.328175,0.000
1,7010,m1,2,3,34063,0.015892,14.442209,0.000
2,7010,m1,3,2,85220,0.006006,4.659174,0.000
3,7010,m1,6,6,945,0.545855,7.400952,0.001
4,7010,m1,12,11,53099,0.001793,2.359713,0.018
...,...,...,...,...,...,...,...,...
2449,7013,m19,53,31,19570,0.025932,27.226430,0.000
2450,7013,m19,54,28,51384,0.002892,3.373544,0.008
2451,7013,m19,55,29,66063,0.002704,2.569091,0.008
2452,7013,m19,56,29,76744,0.001521,3.041195,0.004
2453,7013,m19,57,30,94537,0.001223,3.050993,0.004

In [19]:
hc_place_cells = data[(data['si'] >= 1) & (data['ssi'] >= 3) & (data['best_channel'] <= 16)]
ob_place_cells = data[(data['si'] >= 0.25) & (data['ssi'] >= 3) & (data['best_channel'] >= 16)]

In [20]:
hc_place_cells

,mouse_id,session_id,cluster_id,best_channel,n_spikes,si,ssi,p_value
829,7011,m10,34,10,1326,1.173686,10.251883,0.001
866,7011,m11,37,12,731,2.708767,13.489476,0.001
896,7011,m12,32,12,2206,2.393511,17.620831,0.000
928,7011,m13,42,12,2111,2.532471,50.647860,0.000
1278,7012,m6,29,12,5997,1.324446,30.832160,0.000
1360,7012,m8,17,10,4671,1.052514,16.863506,0.002
1457,7012,m10,29,12,2904,1.487262,27.625550,0.000
1532,7012,m13,31,12,4261,1.786175,35.284345,0.000
1567,7012,m15,16,12,1472,1.841492,36.025452,0.000
1601,7012,m16,18,12,1186,1.837053,39.634186,0.000
1603,7012,m16,20,12,1856,1.879938,29.516068,0.000

In [18]:
ob_place_cells

,mouse_id,session_id,cluster_id,best_channel,n_spikes,si,ssi,p_value
58,7010,m2,52,31,13169,1.056537,13.747145,0.000
621,7010,m20,36,23,2638,0.568228,3.038942,0.024
1016,7011,m19,32,16,13551,0.250292,5.883212,0.000
1020,7011,m19,65,24,4872,0.488975,3.937687,0.002
1021,7011,m19,66,24,4910,0.562190,4.053794,0.002
1024,7011,m19,69,31,9440,0.260641,5.314877,0.000